import type { Metadata } from "next";
import { Section } from "@/components/Section";
import { PageHero } from "@/components/PageHero";
import { ORG } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How The Children's Collective of Florida collects, uses, and protects the information you share with us.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow="Your privacy"
        title="Privacy Policy"
        intro="We collect only what we need to respond to you and steward your support — and we never sell your information."
      />

      <Section background="white">
        <div className="prose-legal">
          <p className="text-sm text-muted">Last updated: June 2026</p>

          <h2>Who we are</h2>
          <p>
            {ORG.legalName} (&ldquo;{ORG.abbr},&rdquo; &ldquo;we,&rdquo;
            &ldquo;us&rdquo;) is a Florida 501(c)(3) public charity. This policy
            explains what information we collect through {ORG.domain} and how we
            use it. Questions? Email{" "}
            <a href={`mailto:${ORG.email}`}>{ORG.email}</a>.
          </p>

          <h2>Information we collect</h2>
          <ul>
            <li>
              <strong>Information you give us through forms</strong> — your name,
              email address, optional phone number, the reason for reaching out,
              and your message, when you use our contact form or sign up to
              follow our launch.
            </li>
            <li>
              <strong>Donation information</strong> — when you give, your payment
              is processed by Stripe. We receive a confirmation with your name,
              email, and gift amount. <strong>We never see or store your full
              card number</strong> — that is handled entirely by Stripe.
            </li>
            <li>
              <strong>Basic technical data</strong> — standard server and
              security logs generated by our hosting provider (e.g., IP address,
              browser type) used to keep the site running and secure.
            </li>
          </ul>

          <h2>How we use it</h2>
          <ul>
            <li>To respond to your message or request.</li>
            <li>
              To send you launch and program updates <em>only if</em> you asked
              to receive them.
            </li>
            <li>To process and acknowledge your donation and send a receipt.</li>
            <li>To operate, secure, and improve our website.</li>
          </ul>

          <h2>Service providers we rely on</h2>
          <p>
            We share information only with the trusted services that make the
            site work, and only as needed:
          </p>
          <ul>
            <li>
              <strong>Stripe</strong> — payment processing for donations.
            </li>
            <li>
              <strong>Supabase</strong> — secure storage of form submissions.
            </li>
            <li>
              <strong>Resend</strong> — delivering form notifications to our
              team.
            </li>
            <li>
              <strong>Netlify</strong> — website hosting.
            </li>
          </ul>
          <p>
            <strong>We do not sell, rent, or trade your personal
            information.</strong>
          </p>

          <h2>Your choices</h2>
          <ul>
            <li>
              You can unsubscribe from launch/update emails at any time using the
              link in those emails or by contacting us.
            </li>
            <li>
              You can ask us to access, correct, or delete the information you
              have shared by emailing{" "}
              <a href={`mailto:${ORG.email}`}>{ORG.email}</a>.
            </li>
          </ul>

          <h2>Children&apos;s privacy</h2>
          <p>
            Our site is intended for adults who wish to support children. We do
            not knowingly collect personal information from children under 13.
          </p>

          <h2>Changes to this policy</h2>
          <p>
            We may update this policy as our programs grow. We&apos;ll revise the
            &ldquo;last updated&rdquo; date above when we do.
          </p>
        </div>
      </Section>
    </>
  );
}
